# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Plastic Metal
author: Plastic Metal
timezone: UTC

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
# root: /

# Writing
relative_link: false

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: ../node_modules/hexo-theme-doc

theme_config:
  favicon: images/favicon.ico
  support:
    link_url: 'mailto:ferdinandsukhoi@outlook.com'
    text: 'Did not you find what are you looking for? Try searching again on the left menu or'
    link_text: 'Contact Us'
    navigation: true
    navigation_label: 'SUPPORT'

ignore:
  # development only: ignore sub node_modules when `npm link hexo-theme-doc`
  - '**/node_modules/**/*node_modules'

##
# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:Plastic-Metal/Plastic-Metal.github.io.git
  branch: master